-- Migration 012: Farmer-Farm binding - consolidate farms per farmer
-- Binds each unique farmer.id to all farm.id via farms.farmer_id
-- Enables single farmer to register and own multiple farms
--
-- Unified farm creation (single database, single farms table):
-- - Farmer app "Add Farm" (farmer-service POST /api/farmers/me/farms)
-- - Admin register farmer (admin-service POST /api/admin/farmers/register)
-- - Admin approve access request (admin-service POST /api/admin/requests/:id/approve)
-- - Admin add farm (admin-service POST /api/admin/farms)
-- All write to farms table; unique_code auto-generated by trigger when NULL.

-- Document the relationship: farms.farmer_id -> farmers.id (one farmer, many farms)
COMMENT ON COLUMN farms.farmer_id IS 'Links farm to owner. One farmer (farmers.id) can own multiple farms.';

COMMENT ON COLUMN farmers.id IS 'Unique farmer identifier. Used by farms.farmer_id to bind all farms belonging to this farmer.';

-- Ensure index for efficient "all farms per farmer" queries
CREATE INDEX IF NOT EXISTS idx_farms_farmer_id_id ON farms(farmer_id, id);
